baseURL = "http://example.org/"
languageCode = "en-us"
relativeURLs = false
title = "Purusothaman Ramanujam"
disqusShortname = "purusothaman-ramanujam"
paginate = 5

[params]
	# Render the rotating globe in the sidebar
	showglobe = true

	# Include favicon
	favicon = "favicon.ico"

	# Email (optional)
	email = "purushoth.r@gmail.com"
	
	# Header Title for the main page
	header = "What I'm Thinking"
	
	# Sidebar profile picture
	profilepic = "img/avatar.jpg"
	
	# Title/subtitle for the sidebar
	title = "Purusothaman Ramanujam"
	subtitle = "My Personal Flavour"
	
	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/purus"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/purusr"
	[[params.socialbuttons]]
